source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'loudspeaker' do
  pod 'loudspeaker', :path => '../'

  target 'Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
  end
end
