target 'loudspeaker', :exclusive => true do
  pod "loudspeaker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "loudspeaker", :path => "../"

  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
  pod 'OCMock', '~> 3.1'
end
