# reference: http://www.objc.io/issue-6/travis-ci.html

osx_image: xcode7.3
language: objective-c
podfile: Example/Podfile
cache:
  - cocoapods
script:
- xctool test -workspace Example/loudspeaker.xcworkspace -scheme Tests -sdk iphonesimulator
